import { GithubProjects } from "@/types/projects"
export const GITHUB_PROJECTS: GithubProjects[] = [  {
    "id": 1128699364,
    "node_id": "R_kgDOQ0aV5A",
    "name": "code-showcase",
    "full_name": "carlosgabrielcampo/code-showcase",
    "private": false,
    "owner": {
      "login": "carlosgabrielcampo",
      "id": 28167638,
      "node_id": "MDQ6VXNlcjI4MTY3NjM4",
      "avatar_url": "https://avatars.githubusercontent.com/u/28167638?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/carlosgabrielcampo",
      "html_url": "https://github.com/carlosgabrielcampo",
      "followers_url": "https://api.github.com/users/carlosgabrielcampo/followers",
      "following_url": "https://api.github.com/users/carlosgabrielcampo/following{/other_user}",
      "gists_url": "https://api.github.com/users/carlosgabrielcampo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/carlosgabrielcampo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/carlosgabrielcampo/subscriptions",
      "organizations_url": "https://api.github.com/users/carlosgabrielcampo/orgs",
      "repos_url": "https://api.github.com/users/carlosgabrielcampo/repos",
      "events_url": "https://api.github.com/users/carlosgabrielcampo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/carlosgabrielcampo/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/carlosgabrielcampo/code-showcase",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase",
    "forks_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/forks",
    "keys_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/teams",
    "hooks_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/hooks",
    "issue_events_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/issues/events{/number}",
    "events_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/events",
    "assignees_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/assignees{/user}",
    "branches_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/branches{/branch}",
    "tags_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/tags",
    "blobs_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/languages",
    "stargazers_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/stargazers",
    "contributors_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/contributors",
    "subscribers_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/subscribers",
    "subscription_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/subscription",
    "commits_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/contents/{+path}",
    "compare_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/merges",
    "archive_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/downloads",
    "issues_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/issues{/number}",
    "pulls_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/labels{/name}",
    "releases_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/releases{/id}",
    "deployments_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/deployments",
    "created_at": "2026-01-06T03:02:36Z",
    "updated_at": "2026-01-09T16:45:42Z",
    "pushed_at": "2026-01-09T16:45:38Z",
    "git_url": "git://github.com/carlosgabrielcampo/code-showcase.git",
    "ssh_url": "git@github.com:carlosgabrielcampo/code-showcase.git",
    "clone_url": "https://github.com/carlosgabrielcampo/code-showcase.git",
    "svn_url": "https://github.com/carlosgabrielcampo/code-showcase",
    "homepage": "https://code-showcase-ten.vercel.app",
    "size": 1822,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "languagePercentage": {
      "JavaScript": 2427783,
      "TypeScript": 258690,
      "CSS": 6410,
      "HTML": 910,
      "React": 0
    },
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": ['typescript', 'css', 'html', 'react'],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  // {
  //   "id": 414340176,
  //   "node_id": "R_kgDOGLJUUA",
  //   "name": "carlosgabrielcampo",
  //   "full_name": "carlosgabrielcampo/carlosgabrielcampo",
  //   "private": false,
  //   "owner": {
  //     "login": "carlosgabrielcampo",
  //     "id": 28167638,
  //     "node_id": "MDQ6VXNlcjI4MTY3NjM4",
  //     "avatar_url": "https://avatars.githubusercontent.com/u/28167638?v=4",
  //     "gravatar_id": "",
  //     "url": "https://api.github.com/users/carlosgabrielcampo",
  //     "html_url": "https://github.com/carlosgabrielcampo",
  //     "followers_url": "https://api.github.com/users/carlosgabrielcampo/followers",
  //     "following_url": "https://api.github.com/users/carlosgabrielcampo/following{/other_user}",
  //     "gists_url": "https://api.github.com/users/carlosgabrielcampo/gists{/gist_id}",
  //     "starred_url": "https://api.github.com/users/carlosgabrielcampo/starred{/owner}{/repo}",
  //     "subscriptions_url": "https://api.github.com/users/carlosgabrielcampo/subscriptions",
  //     "organizations_url": "https://api.github.com/users/carlosgabrielcampo/orgs",
  //     "repos_url": "https://api.github.com/users/carlosgabrielcampo/repos",
  //     "events_url": "https://api.github.com/users/carlosgabrielcampo/events{/privacy}",
  //     "received_events_url": "https://api.github.com/users/carlosgabrielcampo/received_events",
  //     "type": "User",
  //     "user_view_type": "public",
  //     "site_admin": false
  //   },
  //   "html_url": "https://github.com/carlosgabrielcampo/carlosgabrielcampo",
  //   "description": "Config files for my GitHub profile.",
  //   "fork": false,
  //   "url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo",
  //   "forks_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/forks",
  //   "keys_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/keys{/key_id}",
  //   "collaborators_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/collaborators{/collaborator}",
  //   "teams_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/teams",
  //   "hooks_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/hooks",
  //   "issue_events_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/issues/events{/number}",
  //   "events_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/events",
  //   "assignees_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/assignees{/user}",
  //   "branches_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/branches{/branch}",
  //   "tags_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/tags",
  //   "blobs_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/git/blobs{/sha}",
  //   "git_tags_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/git/tags{/sha}",
  //   "git_refs_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/git/refs{/sha}",
  //   "trees_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/git/trees{/sha}",
  //   "statuses_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/statuses/{sha}",
  //   "languages_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/languages",
  //   "stargazers_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/stargazers",
  //   "contributors_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/contributors",
  //   "subscribers_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/subscribers",
  //   "subscription_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/subscription",
  //   "commits_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/commits{/sha}",
  //   "git_commits_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/git/commits{/sha}",
  //   "comments_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/comments{/number}",
  //   "issue_comment_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/issues/comments{/number}",
  //   "contents_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/contents/{+path}",
  //   "compare_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/compare/{base}...{head}",
  //   "merges_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/merges",
  //   "archive_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/{archive_format}{/ref}",
  //   "downloads_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/downloads",
  //   "issues_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/issues{/number}",
  //   "pulls_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/pulls{/number}",
  //   "milestones_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/milestones{/number}",
  //   "notifications_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/notifications{?since,all,participating}",
  //   "labels_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/labels{/name}",
  //   "releases_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/releases{/id}",
  //   "deployments_url": "https://api.github.com/repos/carlosgabrielcampo/carlosgabrielcampo/deployments",
  //   "created_at": "2021-10-06T19:11:20Z",
  //   "updated_at": "2026-01-08T17:26:10Z",
  //   "pushed_at": "2026-01-06T19:18:55Z",
  //   "git_url": "git://github.com/carlosgabrielcampo/carlosgabrielcampo.git",
  //   "ssh_url": "git@github.com:carlosgabrielcampo/carlosgabrielcampo.git",
  //   "clone_url": "https://github.com/carlosgabrielcampo/carlosgabrielcampo.git",
  //   "svn_url": "https://github.com/carlosgabrielcampo/carlosgabrielcampo",
  //   "homepage": "https://github.com/carlosgabrielcampo",
  //   "size": 9,
  //   "stargazers_count": 0,
  //   "watchers_count": 0,
  //   "language": null,
  //   "has_issues": false,
  //   "has_projects": true,
  //   "has_downloads": true,
  //   "has_wiki": false,
  //   "has_pages": false,
  //   "has_discussions": false,
  //   "forks_count": 0,
  //   "mirror_url": null,
  //   "archived": false,
  //   "disabled": false,
  //   "open_issues_count": 0,
  //   "license": null,
  //   "allow_forking": true,
  //   "is_template": false,
  //   "web_commit_signoff_required": false,
  //   "topics": [],
  //   "visibility": "public",
  //   "forks": 0,
  //   "open_issues": 0,
  //   "watchers": 0,
  //   "default_branch": "main"
  // },
  {
    "id": 787660329,
    "node_id": "R_kgDOLvK-KQ",
    "name": "crm-model",
    "full_name": "carlosgabrielcampo/crm-model",
    "private": false,
    "owner": {
      "login": "carlosgabrielcampo",
      "id": 28167638,
      "node_id": "MDQ6VXNlcjI4MTY3NjM4",
      "avatar_url": "https://avatars.githubusercontent.com/u/28167638?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/carlosgabrielcampo",
      "html_url": "https://github.com/carlosgabrielcampo",
      "followers_url": "https://api.github.com/users/carlosgabrielcampo/followers",
      "following_url": "https://api.github.com/users/carlosgabrielcampo/following{/other_user}",
      "gists_url": "https://api.github.com/users/carlosgabrielcampo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/carlosgabrielcampo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/carlosgabrielcampo/subscriptions",
      "organizations_url": "https://api.github.com/users/carlosgabrielcampo/orgs",
      "repos_url": "https://api.github.com/users/carlosgabrielcampo/repos",
      "events_url": "https://api.github.com/users/carlosgabrielcampo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/carlosgabrielcampo/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/carlosgabrielcampo/crm-model",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/carlosgabrielcampo/crm-model",
    "forks_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/forks",
    "keys_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/teams",
    "hooks_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/hooks",
    "issue_events_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/issues/events{/number}",
    "events_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/events",
    "assignees_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/assignees{/user}",
    "branches_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/branches{/branch}",
    "tags_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/tags",
    "blobs_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/languages",
    "stargazers_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/stargazers",
    "contributors_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/contributors",
    "subscribers_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/subscribers",
    "subscription_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/subscription",
    "commits_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/contents/{+path}",
    "compare_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/merges",
    "archive_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/downloads",
    "issues_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/issues{/number}",
    "pulls_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/labels{/name}",
    "releases_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/releases{/id}",
    "deployments_url": "https://api.github.com/repos/carlosgabrielcampo/crm-model/deployments",
    "created_at": "2024-04-17T00:08:23Z",
    "updated_at": "2026-01-08T17:25:39Z",
    "pushed_at": "2024-04-19T02:03:44Z",
    "git_url": "git://github.com/carlosgabrielcampo/crm-model.git",
    "ssh_url": "git@github.com:carlosgabrielcampo/crm-model.git",
    "clone_url": "https://github.com/carlosgabrielcampo/crm-model.git",
    "svn_url": "https://github.com/carlosgabrielcampo/crm-model",
    "homepage": "",
    "size": 1344,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "languagePercentage": {
      "JavaScript": 13473,
      "SCSS": 13152,
      "HTML": 1721,
      "React": 0
    },
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "javascript",
      "react",
      "scss"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  }
]
