import { GithubProjects } from "@/types/projects"
export const GITHUB_PROJECTS: GithubProjects[] = [
  {
    "id": 1086022186,
    "node_id": "R_kgDOQLtiKg",
    "name": "node48-frontend",
    "full_name": "carlosgabrielcampo/node48-frontend",
    "private": false,
    "owner": {
        "login": "carlosgabrielcampo",
        "id": 28167638,
        "node_id": "MDQ6VXNlcjI4MTY3NjM4",
        "avatar_url": "https://avatars.githubusercontent.com/u/28167638?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/carlosgabrielcampo",
        "html_url": "https://github.com/carlosgabrielcampo",
        "followers_url": "https://api.github.com/users/carlosgabrielcampo/followers",
        "following_url": "https://api.github.com/users/carlosgabrielcampo/following{/other_user}",
        "gists_url": "https://api.github.com/users/carlosgabrielcampo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/carlosgabrielcampo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/carlosgabrielcampo/subscriptions",
        "organizations_url": "https://api.github.com/users/carlosgabrielcampo/orgs",
        "repos_url": "https://api.github.com/users/carlosgabrielcampo/repos",
        "events_url": "https://api.github.com/users/carlosgabrielcampo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/carlosgabrielcampo/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
    },
    "html_url": "https://github.com/carlosgabrielcampo/node48-frontend",
    "description": "NODE48 Frontend — React + TypeScript visual workflow editor and orchestration UI",
    "fork": false,
    "url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend",
    "forks_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/forks",
    "keys_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/teams",
    "hooks_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/hooks",
    "issue_events_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/issues/events{/number}",
    "events_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/events",
    "assignees_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/assignees{/user}",
    "branches_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/branches{/branch}",
    "tags_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/tags",
    "blobs_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/languages",
    "stargazers_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/stargazers",
    "contributors_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/contributors",
    "subscribers_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/subscribers",
    "subscription_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/subscription",
    "commits_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/contents/{+path}",
    "compare_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/merges",
    "archive_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/downloads",
    "issues_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/issues{/number}",
    "pulls_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/labels{/name}",
    "releases_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/releases{/id}",
    "deployments_url": "https://api.github.com/repos/carlosgabrielcampo/node48-frontend/deployments",
    "created_at": "2025-10-29T20:48:20Z",
    "updated_at": "2026-01-11T04:01:16Z",
    "pushed_at": "2026-01-11T04:01:13Z",
    "git_url": "git://github.com/carlosgabrielcampo/node48-frontend.git",
    "ssh_url": "git@github.com:carlosgabrielcampo/node48-frontend.git",
    "clone_url": "https://github.com/carlosgabrielcampo/node48-frontend.git",
    "svn_url": "https://github.com/carlosgabrielcampo/node48-frontend",
    "homepage": "https://node48-frontend.vercel.app",
    "size": 774,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "TypeScript",
    "languagePercentage":{
      "TypeScript": 319732,
      "CSS": 3444,
      "JavaScript": 846,
      "HTML": 735
    },
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "TypeScript",
      "CSS",
      "JavaScript",
      "HTML",
      "Tailwind"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1131280286,
    "node_id": "R_kgDOQ233ng",
    "name": "ws-chatbot",
    "full_name": "carlosgabrielcampo/ws-chatbot",
    "private": false,
    "owner": {
        "login": "carlosgabrielcampo",
        "id": 28167638,
        "node_id": "MDQ6VXNlcjI4MTY3NjM4",
        "avatar_url": "https://avatars.githubusercontent.com/u/28167638?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/carlosgabrielcampo",
        "html_url": "https://github.com/carlosgabrielcampo",
        "followers_url": "https://api.github.com/users/carlosgabrielcampo/followers",
        "following_url": "https://api.github.com/users/carlosgabrielcampo/following{/other_user}",
        "gists_url": "https://api.github.com/users/carlosgabrielcampo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/carlosgabrielcampo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/carlosgabrielcampo/subscriptions",
        "organizations_url": "https://api.github.com/users/carlosgabrielcampo/orgs",
        "repos_url": "https://api.github.com/users/carlosgabrielcampo/repos",
        "events_url": "https://api.github.com/users/carlosgabrielcampo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/carlosgabrielcampo/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
    },
    "html_url": "https://github.com/carlosgabrielcampo/ws-chatbot",
    "description": "Node.js WhatsApp chatbot for financial services, integrating multiple banking APIs to automate customer conversations, loan simulations, and business workflows.",
    "fork": false,
    "url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot",
    "forks_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/forks",
    "keys_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/teams",
    "hooks_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/hooks",
    "issue_events_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/issues/events{/number}",
    "events_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/events",
    "assignees_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/assignees{/user}",
    "branches_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/branches{/branch}",
    "tags_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/tags",
    "blobs_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/languages",
    "stargazers_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/stargazers",
    "contributors_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/contributors",
    "subscribers_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/subscribers",
    "subscription_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/subscription",
    "commits_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/contents/{+path}",
    "compare_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/merges",
    "archive_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/downloads",
    "issues_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/issues{/number}",
    "pulls_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/labels{/name}",
    "releases_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/releases{/id}",
    "deployments_url": "https://api.github.com/repos/carlosgabrielcampo/ws-chatbot/deployments",
    "created_at": "2026-01-09T18:45:15Z",
    "updated_at": "2026-01-09T19:42:09Z",
    "pushed_at": "2026-01-09T19:31:36Z",
    "git_url": "git://github.com/carlosgabrielcampo/ws-chatbot.git",
    "ssh_url": "git@github.com:carlosgabrielcampo/ws-chatbot.git",
    "clone_url": "https://github.com/carlosgabrielcampo/ws-chatbot.git",
    "svn_url": "https://github.com/carlosgabrielcampo/ws-chatbot",
    "homepage": "",
    "size": 184,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "languagePercentage": {
      "NodeJs": 366775,
    },
    
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
        "Legacy",
        "NodeJs",
        "puppeteer",
        "REST-API",
        "MongoDB",
        "PostgresSQL"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1128699364,
    "node_id": "R_kgDOQ0aV5A",
    "name": "code-showcase",
    "full_name": "carlosgabrielcampo/code-showcase",
    "private": false,
    "owner": {
      "login": "carlosgabrielcampo",
      "id": 28167638,
      "node_id": "MDQ6VXNlcjI4MTY3NjM4",
      "avatar_url": "https://avatars.githubusercontent.com/u/28167638?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/carlosgabrielcampo",
      "html_url": "https://github.com/carlosgabrielcampo",
      "followers_url": "https://api.github.com/users/carlosgabrielcampo/followers",
      "following_url": "https://api.github.com/users/carlosgabrielcampo/following{/other_user}",
      "gists_url": "https://api.github.com/users/carlosgabrielcampo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/carlosgabrielcampo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/carlosgabrielcampo/subscriptions",
      "organizations_url": "https://api.github.com/users/carlosgabrielcampo/orgs",
      "repos_url": "https://api.github.com/users/carlosgabrielcampo/repos",
      "events_url": "https://api.github.com/users/carlosgabrielcampo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/carlosgabrielcampo/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/carlosgabrielcampo/code-showcase",
    "description": "A personal portfolio built with React, TypeScript, and Vite, focused on clarity, performance, and maintainability.Showcases professional experience, featured projects with filtering, and a data-driven content structure, using Tailwind CSS and shadcn/ui for accessible, composable UI.",
    "fork": false,
    "url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase",
    "forks_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/forks",
    "keys_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/teams",
    "hooks_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/hooks",
    "issue_events_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/issues/events{/number}",
    "events_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/events",
    "assignees_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/assignees{/user}",
    "branches_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/branches{/branch}",
    "tags_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/tags",
    "blobs_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/languages",
    "stargazers_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/stargazers",
    "contributors_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/contributors",
    "subscribers_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/subscribers",
    "subscription_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/subscription",
    "commits_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/contents/{+path}",
    "compare_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/merges",
    "archive_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/downloads",
    "issues_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/issues{/number}",
    "pulls_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/labels{/name}",
    "releases_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/releases{/id}",
    "deployments_url": "https://api.github.com/repos/carlosgabrielcampo/code-showcase/deployments",
    "created_at": "2026-01-06T03:02:36Z",
    "updated_at": "2026-01-09T16:45:42Z",
    "pushed_at": "2026-01-09T16:45:38Z",
    "git_url": "git://github.com/carlosgabrielcampo/code-showcase.git",
    "ssh_url": "git@github.com:carlosgabrielcampo/code-showcase.git",
    "clone_url": "https://github.com/carlosgabrielcampo/code-showcase.git",
    "svn_url": "https://github.com/carlosgabrielcampo/code-showcase",
    "homepage": "https://code-showcase-ten.vercel.app",
    "size": 1822,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "languagePercentage": {
      "JavaScript": 2427783,
      "TypeScript": 258690,
      "CSS": 6410,
      "HTML": 910,
    },
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": ['TypeScript', 'CSS', 'react', 'Tailwind' ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1131329902,
    "node_id": "R_kgDOQ265bg",
    "name": "legacy-database",
    "full_name": "carlosgabrielcampo/legacy-database",
    "private": false,
    "owner": {
      "login": "carlosgabrielcampo",
      "id": 28167638,
      "node_id": "MDQ6VXNlcjI4MTY3NjM4",
      "avatar_url": "https://avatars.githubusercontent.com/u/28167638?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/carlosgabrielcampo",
      "html_url": "https://github.com/carlosgabrielcampo",
      "followers_url": "https://api.github.com/users/carlosgabrielcampo/followers",
      "following_url": "https://api.github.com/users/carlosgabrielcampo/following{/other_user}",
      "gists_url": "https://api.github.com/users/carlosgabrielcampo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/carlosgabrielcampo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/carlosgabrielcampo/subscriptions",
      "organizations_url": "https://api.github.com/users/carlosgabrielcampo/orgs",
      "repos_url": "https://api.github.com/users/carlosgabrielcampo/repos",
      "events_url": "https://api.github.com/users/carlosgabrielcampo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/carlosgabrielcampo/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/carlosgabrielcampo/legacy-database",
    "description": "Legacy Node.js application demonstrating structured PostgreSQL integration using Sequelize, with migrations, Docker support, and an MVC-style architecture for multi-domain business logic.",
    "fork": false,
    "url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database",
    "forks_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/forks",
    "keys_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/teams",
    "hooks_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/hooks",
    "issue_events_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/issues/events{/number}",
    "events_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/events",
    "assignees_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/assignees{/user}",
    "branches_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/branches{/branch}",
    "tags_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/tags",
    "blobs_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/languages",
    "stargazers_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/stargazers",
    "contributors_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/contributors",
    "subscribers_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/subscribers",
    "subscription_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/subscription",
    "commits_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/contents/{+path}",
    "compare_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/merges",
    "archive_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/downloads",
    "issues_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/issues{/number}",
    "pulls_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/labels{/name}",
    "releases_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/releases{/id}",
    "deployments_url": "https://api.github.com/repos/carlosgabrielcampo/legacy-database/deployments",
    "created_at": "2026-01-09T20:38:28Z",
    "updated_at": "2026-01-09T20:58:46Z",
    "pushed_at": "2026-01-09T20:56:33Z",
    "git_url": "git://github.com/carlosgabrielcampo/legacy-database.git",
    "ssh_url": "git@github.com:carlosgabrielcampo/legacy-database.git",
    "clone_url": "https://github.com/carlosgabrielcampo/legacy-database.git",
    "svn_url": "https://github.com/carlosgabrielcampo/legacy-database",
    "homepage": "",
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "languagePercentage": {
      "NodeJs": 158654,
      "Dockerfile": 156
    },
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "Legacy",
      "Docker",
      "NodeJs",
      "PostgresSQL",
      "REST-API",
      "Swagger"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  }
]
